# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

# mongo-lint is a custom linter that is not called in any of the go code.
required = ["github.com/3rf/mongo-lint"]

[[constraint]]
  name = "github.com/mongodb/mongo-tools-common"
  version = "v4.0.2"

[[constraint]]
  name = "github.com/nsf/termbox-go"
  revision = "0723e7c3d0a317dea811f0fbe4d6edd81908c971"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  revision = "bf58a9a1291224109919756b4dcc469c670cc7e4"

[[override]]
  name = "gopkg.in/mgo.v2"
  source = "github.com/10gen/mgo"
  revision = "8c133fd1d0fc316302df84fc12769e17fb473bb1"

[[constraint]]
  name = "gopkg.in/tomb.v2"
  revision = "14b3d72120e8d10ea6e6b7f87f7175734b1faab8"

[[override]]
  name = "github.com/jtolds/gls"
  version = "4.20.0"

[[override]]
  name = "github.com/jacobsa/oglematchers"
  revision = "3ecefc49db07722beca986d9bb71ddd026b133f0"

[[override]]
  name = "github.com/smartystreets/assertions"
  revision = "287b4346dc4e71a038c346375a9d572453bc469b"

[[override]]
  name = "github.com/3rf/mongo-lint"
  revision = "3550fdcf1f43b89aaeabaa4559eaae6dc4407e42"

[[override]]
  name = "github.com/spacemonkeygo/spacelog"
  revision = "f936fb050dc6b5fe4a96b485a6f069e8bdc59aeb"

[[override]]
  name = "github.com/mattn/go-runewidth"
  version = "v0.0.4"

[[override]]
  name = "github.com/golang/snappy"
  revision = "d9eb7a3d35ec988b8585d4a0068e462c27d28380"

[[override]]
  name = "github.com/xdp/stringprep"
  version = "v1.0.0"

[[override]]
  name = "github.com/golang/text"
  version = "v0.3.0"

[prune]
  go-tests = true
  # unused-packages = true

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.3.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.29.11"
